language: node_js
sudo: false

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - 'node'

after_success:
  - npm run coverage
  - npm i codecov
  - nyc report --reporter=text-lcov > coverage.lcov && codecov

notifications:
  email:
    on_success: never
